# Generated by Django 4.2.17 on 2025-06-30 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, help_text='입력된 아이디는 고유한 값을 가짐. (중복불가)<br/>또한 변경 가능하지만, 최종으로 사용된 아이디는 회원 탈퇴가 있더라도 재사용 할 수는 없음', max_length=20, null=True, verbose_name='사용자 검색 등에 사용되는 고유 아이디')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, verbose_name='username')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='password')),
                ('is_confirm', models.BooleanField(default=False, verbose_name='약관 동의 유무')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('provider', models.CharField(blank=True, max_length=10, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자 목록',
                'verbose_name_plural': '사용자 목록',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, max_length=60, null=True, verbose_name='사용자 닉네임')),
                ('gender', models.CharField(blank=True, choices=[('M', '남자'), ('F', '여자'), ('U', '미제공')], max_length=1, null=True, verbose_name='성별')),
                ('birthday', models.DateTimeField(blank=True, help_text='사주 컨텐츠를 활용하기 위해 시간까지 활용', null=True, verbose_name='생일')),
                ('mbti', models.CharField(blank=True, choices=[('ENFJ', 'ENFJ'), ('ENFP', 'ENFP'), ('ENTJ', 'ENTJ'), ('ENTP', 'ENTP'), ('ESFJ', 'ESFJ'), ('ESFP', 'ESFP'), ('ESTJ', 'ESTJ'), ('ESTP', 'ESTP'), ('INFJ', 'INFJ'), ('INFP', 'INFP'), ('INTJ', 'INTJ'), ('INTP', 'INTP'), ('ISFJ', 'ISFJ'), ('ISFP', 'ISFP'), ('ISTJ', 'ISTJ'), ('ISTP', 'ISTP')], max_length=4, null=True, verbose_name='MBTI')),
                ('introduce', models.TextField(blank=True, null=True, verbose_name='프로필 소개')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_removed', False)), fields=('email',), name='unique_email_if_not_removed'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_removed', False)), fields=('username',), name='unique_username_if_not_removed'),
        ),
    ]
