# Generated by Django 4.2.17 on 2025-06-27 02:50

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, help_text='입력된 아이디는 고유한 값을 가짐. (중복불가)<br/>또한 변경 가능하지만, 최종으로 사용된 아이디는 회원 탈퇴가 있더라도 재사용 할 수는 없음', max_length=20, null=True, verbose_name='사용자 검색 등에 사용되는 고유 아이디')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='password')),
                ('is_confirm', models.BooleanField(default=False, verbose_name='약관 동의 유무')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('provider', models.CharField(blank=True, max_length=10, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자 목록',
                'verbose_name_plural': '사용자 목록',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=60, null=True, verbose_name='사용자 닉네임')),
                ('link', models.URLField(blank=True, max_length=255, null=True, verbose_name='개인 사이트 링크')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='사용자 이메일')),
                ('gender', models.CharField(blank=True, choices=[('M', '남자'), ('F', '여자'), ('U', '미제공')], max_length=1, null=True, verbose_name='성별')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='생일')),
                ('introduce', models.TextField(blank=True, null=True, verbose_name='프로필 소개')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
    ]
