# Generated by Django 4.2.17 on 2025-06-12 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=60, null=True, verbose_name='사용자 닉네임')),
                ('link', models.URLField(blank=True, max_length=255, null=True, verbose_name='개인 사이트 링크')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='사용자 이메일')),
                ('gender', models.CharField(blank=True, choices=[('M', '남자'), ('F', '여자'), ('U', '미제공')], max_length=1, null=True, verbose_name='성별')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='생일')),
                ('introduce', models.TextField(blank=True, null=True, verbose_name='프로필 소개')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
    ]
