# Generated by Django 4.2.17 on 2025-06-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email_user_unique_email_if_not_removed'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_removed', False)), fields=('username',), name='unique_username_if_not_removed'),
        ),
    ]
