# Generated by Django 4.2.17 on 2025-06-30 05:19

import api_server.oauth.models
from django.db import migrations, models
import django.utils.timezone
import encrypted_fields.fields
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthWithApple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_id', models.CharField(max_length=127, unique=True)),
            ],
            options={
                'verbose_name': 'Apple 인증 내역',
                'verbose_name_plural': 'Apple 인증 내역',
                'db_table': 'users_auth_with_apple',
            },
        ),
        migrations.CreateModel(
            name='AuthWithGoogle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_id', models.CharField(max_length=127, unique=True)),
            ],
            options={
                'verbose_name': '구글 인증 내역',
                'verbose_name_plural': '구글 인증 내역',
                'db_table': 'users_auth_with_google',
            },
        ),
        migrations.CreateModel(
            name='AuthWithKakao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_id', models.CharField(max_length=127, unique=True)),
            ],
            options={
                'db_table': 'users_auth_with_kakao',
            },
        ),
        migrations.CreateModel(
            name='AuthWithNaver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_id', models.CharField(max_length=127, unique=True)),
            ],
            options={
                'verbose_name': '네이버 인증 내역',
                'verbose_name_plural': '네이버 인증 내역',
                'db_table': 'users_auth_with_naver',
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_ip', api_server.oauth.models.EncryptedIpAddressField()),
                ('ip', encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_ip', hash_key='365af0a8444b7769fd842152976a43c5aafb3e3c74107a2a4620b77e93fd4420', max_length=66, null=True, verbose_name='접속 IP')),
            ],
            options={
                'verbose_name': '로그인 내역',
                'verbose_name_plural': '로그인 내역',
                'db_table': 'users_login_history',
                'ordering': ['-created'],
            },
        ),
    ]
