# Generated by Django 4.2.17 on 2025-06-30 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authwithnaver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_naver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authwithkakao',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_kakao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authwithgoogle',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_google', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authwithapple',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_apple', to=settings.AUTH_USER_MODEL),
        ),
    ]
