# Generated by Django 4.2.17 on 2025-06-30 04:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('object_id', models.UUIDField()),
                ('image_url', models.URLField(max_length=255, verbose_name='이미지 URL')),
                ('scale', models.CharField(choices=[('RAW', '원본'), ('DETAIL', '상세'), ('NORMAL', '일반'), ('THUMBNAIL', '미리보기'), ('AVATAR', '아바타')], max_length=10, verbose_name='이미지 스케일')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '이미지',
                'verbose_name_plural': '이미지',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='images_imag_content_691509_idx')],
            },
        ),
    ]
